[build]
  base = "frontend"
  publish = "."
  command = ""

# Không sử dụng redirect 200 cho dự án nhiều file HTML (MPA)
# Chỉ sử dụng 404 redirect nếu cần thiết
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
